// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nestedenum.proto

package org.apache.spark.sql.protobuf.protos;

public final class NestedEnumProto {
  private NestedEnumProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code org.apache.spark.sql.protobuf.protos.NestedEnum}
   */
  public enum NestedEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NESTED_NOTHING = 0;</code>
     */
    NESTED_NOTHING(0),
    /**
     * <code>NESTED_FIRST = 1;</code>
     */
    NESTED_FIRST(1),
    /**
     * <code>NESTED_SECOND = 2;</code>
     */
    NESTED_SECOND(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NESTED_NOTHING = 0;</code>
     */
    public static final int NESTED_NOTHING_VALUE = 0;
    /**
     * <code>NESTED_FIRST = 1;</code>
     */
    public static final int NESTED_FIRST_VALUE = 1;
    /**
     * <code>NESTED_SECOND = 2;</code>
     */
    public static final int NESTED_SECOND_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static NestedEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static NestedEnum forNumber(int value) {
      switch (value) {
        case 0: return NESTED_NOTHING;
        case 1: return NESTED_FIRST;
        case 2: return NESTED_SECOND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<NestedEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        NestedEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<NestedEnum>() {
            public NestedEnum findValueByNumber(int number) {
              return NestedEnum.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.apache.spark.sql.protobuf.protos.NestedEnumProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final NestedEnum[] VALUES = values();

    public static NestedEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private NestedEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.apache.spark.sql.protobuf.protos.NestedEnum)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020nestedenum.proto\022$org.apache.spark.sql" +
      ".protobuf.protos*E\n\nNestedEnum\022\022\n\016NESTED" +
      "_NOTHING\020\000\022\020\n\014NESTED_FIRST\020\001\022\021\n\rNESTED_S" +
      "ECOND\020\002B\021B\017NestedEnumProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
