// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spark/connect/relations.proto

package org.apache.spark.connect.proto;

public interface CachedLocalRelationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spark.connect.CachedLocalRelation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * (Required) An identifier of the user which created the local relation
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * (Required) An identifier of the user which created the local relation
   * </pre>
   *
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * (Required) An identifier of the Spark SQL session in which the user created the local relation.
   * </pre>
   *
   * <code>string sessionId = 2;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * (Required) An identifier of the Spark SQL session in which the user created the local relation.
   * </pre>
   *
   * <code>string sessionId = 2;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * (Required) A sha-256 hash of the serialized local relation in proto, see LocalRelation.
   * </pre>
   *
   * <code>string hash = 3;</code>
   * @return The hash.
   */
  java.lang.String getHash();
  /**
   * <pre>
   * (Required) A sha-256 hash of the serialized local relation in proto, see LocalRelation.
   * </pre>
   *
   * <code>string hash = 3;</code>
   * @return The bytes for hash.
   */
  com.google.protobuf.ByteString
      getHashBytes();
}
