// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spark/connect/commands.proto

package org.apache.spark.connect.proto;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_SqlCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_SqlCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_SqlCommand_ArgsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_SqlCommand_ArgsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_CreateDataFrameViewCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_CreateDataFrameViewCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteOperation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteOperation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteOperation_OptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteOperation_OptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteOperation_SaveTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteOperation_SaveTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteOperation_BucketBy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteOperation_BucketBy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteOperationV2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteOperationV2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteOperationV2_OptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteOperationV2_OptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteOperationV2_TablePropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteOperationV2_TablePropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteStreamOperationStart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteStreamOperationStart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteStreamOperationStart_OptionsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteStreamOperationStart_OptionsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingForeachFunction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingForeachFunction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_WriteStreamOperationStartResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_WriteStreamOperationStartResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryInstanceId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryInstanceId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommand_ExplainCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommand_ExplainCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommand_AwaitTerminationCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommand_AwaitTerminationCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommandResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommandResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommandResult_StatusResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommandResult_StatusResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommandResult_RecentProgressResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommandResult_RecentProgressResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommandResult_ExplainResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommandResult_ExplainResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommandResult_ExceptionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommandResult_ExceptionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryCommandResult_AwaitTerminationResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryCommandResult_AwaitTerminationResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommand_AwaitAnyTerminationCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommand_AwaitAnyTerminationCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommand_StreamingQueryListenerCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommand_StreamingQueryListenerCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommandResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommandResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommandResult_ActiveResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommandResult_ActiveResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryInstance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryInstance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommandResult_AwaitAnyTerminationResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommandResult_AwaitAnyTerminationResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryListenerInstance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryListenerInstance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_StreamingQueryManagerCommandResult_ListStreamingQueryListenerResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_StreamingQueryManagerCommandResult_ListStreamingQueryListenerResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_GetResourcesCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_GetResourcesCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_GetResourcesCommandResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_GetResourcesCommandResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spark_connect_GetResourcesCommandResult_ResourcesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_spark_connect_GetResourcesCommandResult_ResourcesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034spark/connect/commands.proto\022\rspark.co" +
      "nnect\032\031google/protobuf/any.proto\032\032spark/" +
      "connect/common.proto\032\037spark/connect/expr" +
      "essions.proto\032\035spark/connect/relations.p" +
      "roto\"\231\006\n\007Command\022K\n\021register_function\030\001 " +
      "\001(\0132..spark.connect.CommonInlineUserDefi" +
      "nedFunctionH\000\0228\n\017write_operation\030\002 \001(\0132\035" +
      ".spark.connect.WriteOperationH\000\022J\n\025creat" +
      "e_dataframe_view\030\003 \001(\0132).spark.connect.C" +
      "reateDataFrameViewCommandH\000\022=\n\022write_ope" +
      "ration_v2\030\004 \001(\0132\037.spark.connect.WriteOpe" +
      "rationV2H\000\0220\n\013sql_command\030\005 \001(\0132\031.spark." +
      "connect.SqlCommandH\000\022P\n\034write_stream_ope" +
      "ration_start\030\006 \001(\0132(.spark.connect.Write" +
      "StreamOperationStartH\000\022G\n\027streaming_quer" +
      "y_command\030\007 \001(\0132$.spark.connect.Streamin" +
      "gQueryCommandH\000\022C\n\025get_resources_command" +
      "\030\010 \001(\0132\".spark.connect.GetResourcesComma" +
      "ndH\000\022V\n\037streaming_query_manager_command\030" +
      "\t \001(\0132+.spark.connect.StreamingQueryMana" +
      "gerCommandH\000\022V\n\027register_table_function\030" +
      "\n \001(\01323.spark.connect.CommonInlineUserDe" +
      "finedTableFunctionH\000\022*\n\textension\030\347\007 \001(\013" +
      "2\024.google.protobuf.AnyH\000B\016\n\014command_type" +
      "\"\321\001\n\nSqlCommand\022\013\n\003sql\030\001 \001(\t\0221\n\004args\030\002 \003" +
      "(\0132#.spark.connect.SqlCommand.ArgsEntry\022" +
      "3\n\010pos_args\030\003 \003(\0132!.spark.connect.Expres" +
      "sion.Literal\032N\n\tArgsEntry\022\013\n\003key\030\001 \001(\t\0220" +
      "\n\005value\030\002 \001(\0132!.spark.connect.Expression" +
      ".Literal:\0028\001\"v\n\032CreateDataFrameViewComma" +
      "nd\022&\n\005input\030\001 \001(\0132\027.spark.connect.Relati" +
      "on\022\014\n\004name\030\002 \001(\t\022\021\n\tis_global\030\003 \001(\010\022\017\n\007r" +
      "eplace\030\004 \001(\010\"\376\006\n\016WriteOperation\022&\n\005input" +
      "\030\001 \001(\0132\027.spark.connect.Relation\022\023\n\006sourc" +
      "e\030\002 \001(\tH\001\210\001\001\022\016\n\004path\030\003 \001(\tH\000\0228\n\005table\030\004 " +
      "\001(\0132\'.spark.connect.WriteOperation.SaveT" +
      "ableH\000\0224\n\004mode\030\005 \001(\0162&.spark.connect.Wri" +
      "teOperation.SaveMode\022\031\n\021sort_column_name" +
      "s\030\006 \003(\t\022\034\n\024partitioning_columns\030\007 \003(\t\0229\n" +
      "\tbucket_by\030\010 \001(\0132&.spark.connect.WriteOp" +
      "eration.BucketBy\022;\n\007options\030\t \003(\0132*.spar" +
      "k.connect.WriteOperation.OptionsEntry\032.\n" +
      "\014OptionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(" +
      "\t:\0028\001\032\353\001\n\tSaveTable\022\022\n\ntable_name\030\001 \001(\t\022" +
      "L\n\013save_method\030\002 \001(\01627.spark.connect.Wri" +
      "teOperation.SaveTable.TableSaveMethod\"|\n" +
      "\017TableSaveMethod\022!\n\035TABLE_SAVE_METHOD_UN" +
      "SPECIFIED\020\000\022#\n\037TABLE_SAVE_METHOD_SAVE_AS" +
      "_TABLE\020\001\022!\n\035TABLE_SAVE_METHOD_INSERT_INT" +
      "O\020\002\032<\n\010BucketBy\022\033\n\023bucket_column_names\030\001" +
      " \003(\t\022\023\n\013num_buckets\030\002 \001(\005\"\211\001\n\010SaveMode\022\031" +
      "\n\025SAVE_MODE_UNSPECIFIED\020\000\022\024\n\020SAVE_MODE_A" +
      "PPEND\020\001\022\027\n\023SAVE_MODE_OVERWRITE\020\002\022\035\n\031SAVE" +
      "_MODE_ERROR_IF_EXISTS\020\003\022\024\n\020SAVE_MODE_IGN" +
      "ORE\020\004B\013\n\tsave_typeB\t\n\007_source\"\260\005\n\020WriteO" +
      "perationV2\022&\n\005input\030\001 \001(\0132\027.spark.connec" +
      "t.Relation\022\022\n\ntable_name\030\002 \001(\t\022\025\n\010provid" +
      "er\030\003 \001(\tH\000\210\001\001\0227\n\024partitioning_columns\030\004 " +
      "\003(\0132\031.spark.connect.Expression\022=\n\007option" +
      "s\030\005 \003(\0132,.spark.connect.WriteOperationV2" +
      ".OptionsEntry\022N\n\020table_properties\030\006 \003(\0132" +
      "4.spark.connect.WriteOperationV2.TablePr" +
      "opertiesEntry\0222\n\004mode\030\007 \001(\0162$.spark.conn" +
      "ect.WriteOperationV2.Mode\0226\n\023overwrite_c" +
      "ondition\030\010 \001(\0132\031.spark.connect.Expressio" +
      "n\032.\n\014OptionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\0326\n\024TablePropertiesEntry\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\237\001\n\004Mode\022\024\n\020MO" +
      "DE_UNSPECIFIED\020\000\022\017\n\013MODE_CREATE\020\001\022\022\n\016MOD" +
      "E_OVERWRITE\020\002\022\035\n\031MODE_OVERWRITE_PARTITIO" +
      "NS\020\003\022\017\n\013MODE_APPEND\020\004\022\020\n\014MODE_REPLACE\020\005\022" +
      "\032\n\026MODE_CREATE_OR_REPLACE\020\006B\013\n\t_provider" +
      "\"\324\004\n\031WriteStreamOperationStart\022&\n\005input\030" +
      "\001 \001(\0132\027.spark.connect.Relation\022\016\n\006format" +
      "\030\002 \001(\t\022F\n\007options\030\003 \003(\01325.spark.connect." +
      "WriteStreamOperationStart.OptionsEntry\022!" +
      "\n\031partitioning_column_names\030\004 \003(\t\022\"\n\030pro" +
      "cessing_time_interval\030\005 \001(\tH\000\022\027\n\ravailab" +
      "le_now\030\006 \001(\010H\000\022\016\n\004once\030\007 \001(\010H\000\022(\n\036contin" +
      "uous_checkpoint_interval\030\010 \001(\tH\000\022\023\n\013outp" +
      "ut_mode\030\t \001(\t\022\022\n\nquery_name\030\n \001(\t\022\016\n\004pat" +
      "h\030\013 \001(\tH\001\022\024\n\ntable_name\030\014 \001(\tH\001\022?\n\016forea" +
      "ch_writer\030\r \001(\0132\'.spark.connect.Streamin" +
      "gForeachFunction\022>\n\rforeach_batch\030\016 \001(\0132" +
      "\'.spark.connect.StreamingForeachFunction" +
      "\032.\n\014OptionsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001B\t\n\007triggerB\022\n\020sink_destination\"" +
      "\224\001\n\030StreamingForeachFunction\0223\n\017python_f" +
      "unction\030\001 \001(\0132\030.spark.connect.PythonUDFH" +
      "\000\0227\n\016scala_function\030\002 \001(\0132\035.spark.connec" +
      "t.ScalarScalaUDFH\000B\n\n\010function\"j\n\037WriteS" +
      "treamOperationStartResult\0229\n\010query_id\030\001 " +
      "\001(\0132\'.spark.connect.StreamingQueryInstan" +
      "ceId\022\014\n\004name\030\002 \001(\t\"6\n\030StreamingQueryInst" +
      "anceId\022\n\n\002id\030\001 \001(\t\022\016\n\006run_id\030\002 \001(\t\"\363\003\n\025S" +
      "treamingQueryCommand\0229\n\010query_id\030\001 \001(\0132\'" +
      ".spark.connect.StreamingQueryInstanceId\022" +
      "\020\n\006status\030\002 \001(\010H\000\022\027\n\rlast_progress\030\003 \001(\010" +
      "H\000\022\031\n\017recent_progress\030\004 \001(\010H\000\022\016\n\004stop\030\005 " +
      "\001(\010H\000\022\037\n\025process_all_available\030\006 \001(\010H\000\022F" +
      "\n\007explain\030\007 \001(\01323.spark.connect.Streamin" +
      "gQueryCommand.ExplainCommandH\000\022\023\n\texcept" +
      "ion\030\010 \001(\010H\000\022Y\n\021await_termination\030\t \001(\0132<" +
      ".spark.connect.StreamingQueryCommand.Awa" +
      "itTerminationCommandH\000\032\"\n\016ExplainCommand" +
      "\022\020\n\010extended\030\001 \001(\010\032A\n\027AwaitTerminationCo" +
      "mmand\022\027\n\ntimeout_ms\030\002 \001(\003H\000\210\001\001B\r\n\013_timeo" +
      "ut_msB\t\n\007command\"\240\007\n\033StreamingQueryComma" +
      "ndResult\0229\n\010query_id\030\001 \001(\0132\'.spark.conne" +
      "ct.StreamingQueryInstanceId\022I\n\006status\030\002 " +
      "\001(\01327.spark.connect.StreamingQueryComman" +
      "dResult.StatusResultH\000\022Z\n\017recent_progres" +
      "s\030\003 \001(\0132?.spark.connect.StreamingQueryCo" +
      "mmandResult.RecentProgressResultH\000\022K\n\007ex" +
      "plain\030\004 \001(\01328.spark.connect.StreamingQue" +
      "ryCommandResult.ExplainResultH\000\022O\n\texcep" +
      "tion\030\005 \001(\0132:.spark.connect.StreamingQuer" +
      "yCommandResult.ExceptionResultH\000\022^\n\021awai" +
      "t_termination\030\006 \001(\0132A.spark.connect.Stre" +
      "amingQueryCommandResult.AwaitTermination" +
      "ResultH\000\032o\n\014StatusResult\022\026\n\016status_messa" +
      "ge\030\001 \001(\t\022\031\n\021is_data_available\030\002 \001(\010\022\031\n\021i" +
      "s_trigger_active\030\003 \001(\010\022\021\n\tis_active\030\004 \001(" +
      "\010\0324\n\024RecentProgressResult\022\034\n\024recent_prog" +
      "ress_json\030\005 \003(\t\032\037\n\rExplainResult\022\016\n\006resu" +
      "lt\030\001 \001(\t\032\233\001\n\017ExceptionResult\022\036\n\021exceptio" +
      "n_message\030\001 \001(\tH\000\210\001\001\022\030\n\013error_class\030\002 \001(" +
      "\tH\001\210\001\001\022\030\n\013stack_trace\030\003 \001(\tH\002\210\001\001B\024\n\022_exc" +
      "eption_messageB\016\n\014_error_classB\016\n\014_stack" +
      "_trace\032,\n\026AwaitTerminationResult\022\022\n\nterm" +
      "inated\030\001 \001(\010B\r\n\013result_type\"\242\005\n\034Streamin" +
      "gQueryManagerCommand\022\020\n\006active\030\001 \001(\010H\000\022\023" +
      "\n\tget_query\030\002 \001(\tH\000\022g\n\025await_any_termina" +
      "tion\030\003 \001(\0132F.spark.connect.StreamingQuer" +
      "yManagerCommand.AwaitAnyTerminationComma" +
      "ndH\000\022\032\n\020reset_terminated\030\004 \001(\010H\000\022a\n\014add_" +
      "listener\030\005 \001(\0132I.spark.connect.Streaming" +
      "QueryManagerCommand.StreamingQueryListen" +
      "erCommandH\000\022d\n\017remove_listener\030\006 \001(\0132I.s" +
      "park.connect.StreamingQueryManagerComman" +
      "d.StreamingQueryListenerCommandH\000\022\030\n\016lis" +
      "t_listeners\030\007 \001(\010H\000\032D\n\032AwaitAnyTerminati" +
      "onCommand\022\027\n\ntimeout_ms\030\001 \001(\003H\000\210\001\001B\r\n\013_t" +
      "imeout_ms\032\241\001\n\035StreamingQueryListenerComm" +
      "and\022\030\n\020listener_payload\030\001 \001(\014\022>\n\027python_" +
      "listener_payload\030\002 \001(\0132\030.spark.connect.P" +
      "ythonUDFH\000\210\001\001\022\n\n\002id\030\003 \001(\tB\032\n\030_python_lis" +
      "tener_payloadB\t\n\007command\"\217\007\n\"StreamingQu" +
      "eryManagerCommandResult\022P\n\006active\030\001 \001(\0132" +
      ">.spark.connect.StreamingQueryManagerCom" +
      "mandResult.ActiveResultH\000\022Y\n\005query\030\002 \001(\013" +
      "2H.spark.connect.StreamingQueryManagerCo" +
      "mmandResult.StreamingQueryInstanceH\000\022l\n\025" +
      "await_any_termination\030\003 \001(\0132K.spark.conn" +
      "ect.StreamingQueryManagerCommandResult.A" +
      "waitAnyTerminationResultH\000\022\032\n\020reset_term" +
      "inated\030\004 \001(\010H\000\022\026\n\014add_listener\030\005 \001(\010H\000\022\031" +
      "\n\017remove_listener\030\006 \001(\010H\000\022l\n\016list_listen" +
      "ers\030\007 \001(\0132R.spark.connect.StreamingQuery" +
      "ManagerCommandResult.ListStreamingQueryL" +
      "istenerResultH\000\032p\n\014ActiveResult\022`\n\016activ" +
      "e_queries\030\001 \003(\0132H.spark.connect.Streamin" +
      "gQueryManagerCommandResult.StreamingQuer" +
      "yInstance\032i\n\026StreamingQueryInstance\0223\n\002i" +
      "d\030\001 \001(\0132\'.spark.connect.StreamingQueryIn" +
      "stanceId\022\021\n\004name\030\002 \001(\tH\000\210\001\001B\007\n\005_name\032/\n\031" +
      "AwaitAnyTerminationResult\022\022\n\nterminated\030" +
      "\001 \001(\010\032:\n\036StreamingQueryListenerInstance\022" +
      "\030\n\020listener_payload\030\001 \001(\014\0328\n ListStreami" +
      "ngQueryListenerResult\022\024\n\014listener_ids\030\001 " +
      "\003(\tB\r\n\013result_type\"\025\n\023GetResourcesComman" +
      "d\"\275\001\n\031GetResourcesCommandResult\022J\n\tresou" +
      "rces\030\001 \003(\01327.spark.connect.GetResourcesC" +
      "ommandResult.ResourcesEntry\032T\n\016Resources" +
      "Entry\022\013\n\003key\030\001 \001(\t\0221\n\005value\030\002 \001(\0132\".spar" +
      "k.connect.ResourceInformation:\0028\001B6\n\036org" +
      ".apache.spark.connect.protoP\001Z\022internal/" +
      "generatedb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          org.apache.spark.connect.proto.Common.getDescriptor(),
          org.apache.spark.connect.proto.Expressions.getDescriptor(),
          org.apache.spark.connect.proto.Relations.getDescriptor(),
        });
    internal_static_spark_connect_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_spark_connect_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_Command_descriptor,
        new java.lang.String[] { "RegisterFunction", "WriteOperation", "CreateDataframeView", "WriteOperationV2", "SqlCommand", "WriteStreamOperationStart", "StreamingQueryCommand", "GetResourcesCommand", "StreamingQueryManagerCommand", "RegisterTableFunction", "Extension", "CommandType", });
    internal_static_spark_connect_SqlCommand_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_spark_connect_SqlCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_SqlCommand_descriptor,
        new java.lang.String[] { "Sql", "Args", "PosArgs", });
    internal_static_spark_connect_SqlCommand_ArgsEntry_descriptor =
      internal_static_spark_connect_SqlCommand_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_SqlCommand_ArgsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_SqlCommand_ArgsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spark_connect_CreateDataFrameViewCommand_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_spark_connect_CreateDataFrameViewCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_CreateDataFrameViewCommand_descriptor,
        new java.lang.String[] { "Input", "Name", "IsGlobal", "Replace", });
    internal_static_spark_connect_WriteOperation_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_spark_connect_WriteOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteOperation_descriptor,
        new java.lang.String[] { "Input", "Source", "Path", "Table", "Mode", "SortColumnNames", "PartitioningColumns", "BucketBy", "Options", "SaveType", "Source", });
    internal_static_spark_connect_WriteOperation_OptionsEntry_descriptor =
      internal_static_spark_connect_WriteOperation_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_WriteOperation_OptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteOperation_OptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spark_connect_WriteOperation_SaveTable_descriptor =
      internal_static_spark_connect_WriteOperation_descriptor.getNestedTypes().get(1);
    internal_static_spark_connect_WriteOperation_SaveTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteOperation_SaveTable_descriptor,
        new java.lang.String[] { "TableName", "SaveMethod", });
    internal_static_spark_connect_WriteOperation_BucketBy_descriptor =
      internal_static_spark_connect_WriteOperation_descriptor.getNestedTypes().get(2);
    internal_static_spark_connect_WriteOperation_BucketBy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteOperation_BucketBy_descriptor,
        new java.lang.String[] { "BucketColumnNames", "NumBuckets", });
    internal_static_spark_connect_WriteOperationV2_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_spark_connect_WriteOperationV2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteOperationV2_descriptor,
        new java.lang.String[] { "Input", "TableName", "Provider", "PartitioningColumns", "Options", "TableProperties", "Mode", "OverwriteCondition", "Provider", });
    internal_static_spark_connect_WriteOperationV2_OptionsEntry_descriptor =
      internal_static_spark_connect_WriteOperationV2_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_WriteOperationV2_OptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteOperationV2_OptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spark_connect_WriteOperationV2_TablePropertiesEntry_descriptor =
      internal_static_spark_connect_WriteOperationV2_descriptor.getNestedTypes().get(1);
    internal_static_spark_connect_WriteOperationV2_TablePropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteOperationV2_TablePropertiesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spark_connect_WriteStreamOperationStart_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_spark_connect_WriteStreamOperationStart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteStreamOperationStart_descriptor,
        new java.lang.String[] { "Input", "Format", "Options", "PartitioningColumnNames", "ProcessingTimeInterval", "AvailableNow", "Once", "ContinuousCheckpointInterval", "OutputMode", "QueryName", "Path", "TableName", "ForeachWriter", "ForeachBatch", "Trigger", "SinkDestination", });
    internal_static_spark_connect_WriteStreamOperationStart_OptionsEntry_descriptor =
      internal_static_spark_connect_WriteStreamOperationStart_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_WriteStreamOperationStart_OptionsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteStreamOperationStart_OptionsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spark_connect_StreamingForeachFunction_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_spark_connect_StreamingForeachFunction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingForeachFunction_descriptor,
        new java.lang.String[] { "PythonFunction", "ScalaFunction", "Function", });
    internal_static_spark_connect_WriteStreamOperationStartResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_spark_connect_WriteStreamOperationStartResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_WriteStreamOperationStartResult_descriptor,
        new java.lang.String[] { "QueryId", "Name", });
    internal_static_spark_connect_StreamingQueryInstanceId_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_spark_connect_StreamingQueryInstanceId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryInstanceId_descriptor,
        new java.lang.String[] { "Id", "RunId", });
    internal_static_spark_connect_StreamingQueryCommand_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_spark_connect_StreamingQueryCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommand_descriptor,
        new java.lang.String[] { "QueryId", "Status", "LastProgress", "RecentProgress", "Stop", "ProcessAllAvailable", "Explain", "Exception", "AwaitTermination", "Command", });
    internal_static_spark_connect_StreamingQueryCommand_ExplainCommand_descriptor =
      internal_static_spark_connect_StreamingQueryCommand_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_StreamingQueryCommand_ExplainCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommand_ExplainCommand_descriptor,
        new java.lang.String[] { "Extended", });
    internal_static_spark_connect_StreamingQueryCommand_AwaitTerminationCommand_descriptor =
      internal_static_spark_connect_StreamingQueryCommand_descriptor.getNestedTypes().get(1);
    internal_static_spark_connect_StreamingQueryCommand_AwaitTerminationCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommand_AwaitTerminationCommand_descriptor,
        new java.lang.String[] { "TimeoutMs", "TimeoutMs", });
    internal_static_spark_connect_StreamingQueryCommandResult_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_spark_connect_StreamingQueryCommandResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommandResult_descriptor,
        new java.lang.String[] { "QueryId", "Status", "RecentProgress", "Explain", "Exception", "AwaitTermination", "ResultType", });
    internal_static_spark_connect_StreamingQueryCommandResult_StatusResult_descriptor =
      internal_static_spark_connect_StreamingQueryCommandResult_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_StreamingQueryCommandResult_StatusResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommandResult_StatusResult_descriptor,
        new java.lang.String[] { "StatusMessage", "IsDataAvailable", "IsTriggerActive", "IsActive", });
    internal_static_spark_connect_StreamingQueryCommandResult_RecentProgressResult_descriptor =
      internal_static_spark_connect_StreamingQueryCommandResult_descriptor.getNestedTypes().get(1);
    internal_static_spark_connect_StreamingQueryCommandResult_RecentProgressResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommandResult_RecentProgressResult_descriptor,
        new java.lang.String[] { "RecentProgressJson", });
    internal_static_spark_connect_StreamingQueryCommandResult_ExplainResult_descriptor =
      internal_static_spark_connect_StreamingQueryCommandResult_descriptor.getNestedTypes().get(2);
    internal_static_spark_connect_StreamingQueryCommandResult_ExplainResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommandResult_ExplainResult_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_spark_connect_StreamingQueryCommandResult_ExceptionResult_descriptor =
      internal_static_spark_connect_StreamingQueryCommandResult_descriptor.getNestedTypes().get(3);
    internal_static_spark_connect_StreamingQueryCommandResult_ExceptionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommandResult_ExceptionResult_descriptor,
        new java.lang.String[] { "ExceptionMessage", "ErrorClass", "StackTrace", "ExceptionMessage", "ErrorClass", "StackTrace", });
    internal_static_spark_connect_StreamingQueryCommandResult_AwaitTerminationResult_descriptor =
      internal_static_spark_connect_StreamingQueryCommandResult_descriptor.getNestedTypes().get(4);
    internal_static_spark_connect_StreamingQueryCommandResult_AwaitTerminationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryCommandResult_AwaitTerminationResult_descriptor,
        new java.lang.String[] { "Terminated", });
    internal_static_spark_connect_StreamingQueryManagerCommand_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_spark_connect_StreamingQueryManagerCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommand_descriptor,
        new java.lang.String[] { "Active", "GetQuery", "AwaitAnyTermination", "ResetTerminated", "AddListener", "RemoveListener", "ListListeners", "Command", });
    internal_static_spark_connect_StreamingQueryManagerCommand_AwaitAnyTerminationCommand_descriptor =
      internal_static_spark_connect_StreamingQueryManagerCommand_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_StreamingQueryManagerCommand_AwaitAnyTerminationCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommand_AwaitAnyTerminationCommand_descriptor,
        new java.lang.String[] { "TimeoutMs", "TimeoutMs", });
    internal_static_spark_connect_StreamingQueryManagerCommand_StreamingQueryListenerCommand_descriptor =
      internal_static_spark_connect_StreamingQueryManagerCommand_descriptor.getNestedTypes().get(1);
    internal_static_spark_connect_StreamingQueryManagerCommand_StreamingQueryListenerCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommand_StreamingQueryListenerCommand_descriptor,
        new java.lang.String[] { "ListenerPayload", "PythonListenerPayload", "Id", "PythonListenerPayload", });
    internal_static_spark_connect_StreamingQueryManagerCommandResult_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_spark_connect_StreamingQueryManagerCommandResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommandResult_descriptor,
        new java.lang.String[] { "Active", "Query", "AwaitAnyTermination", "ResetTerminated", "AddListener", "RemoveListener", "ListListeners", "ResultType", });
    internal_static_spark_connect_StreamingQueryManagerCommandResult_ActiveResult_descriptor =
      internal_static_spark_connect_StreamingQueryManagerCommandResult_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_StreamingQueryManagerCommandResult_ActiveResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommandResult_ActiveResult_descriptor,
        new java.lang.String[] { "ActiveQueries", });
    internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryInstance_descriptor =
      internal_static_spark_connect_StreamingQueryManagerCommandResult_descriptor.getNestedTypes().get(1);
    internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryInstance_descriptor,
        new java.lang.String[] { "Id", "Name", "Name", });
    internal_static_spark_connect_StreamingQueryManagerCommandResult_AwaitAnyTerminationResult_descriptor =
      internal_static_spark_connect_StreamingQueryManagerCommandResult_descriptor.getNestedTypes().get(2);
    internal_static_spark_connect_StreamingQueryManagerCommandResult_AwaitAnyTerminationResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommandResult_AwaitAnyTerminationResult_descriptor,
        new java.lang.String[] { "Terminated", });
    internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryListenerInstance_descriptor =
      internal_static_spark_connect_StreamingQueryManagerCommandResult_descriptor.getNestedTypes().get(3);
    internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryListenerInstance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommandResult_StreamingQueryListenerInstance_descriptor,
        new java.lang.String[] { "ListenerPayload", });
    internal_static_spark_connect_StreamingQueryManagerCommandResult_ListStreamingQueryListenerResult_descriptor =
      internal_static_spark_connect_StreamingQueryManagerCommandResult_descriptor.getNestedTypes().get(4);
    internal_static_spark_connect_StreamingQueryManagerCommandResult_ListStreamingQueryListenerResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_StreamingQueryManagerCommandResult_ListStreamingQueryListenerResult_descriptor,
        new java.lang.String[] { "ListenerIds", });
    internal_static_spark_connect_GetResourcesCommand_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_spark_connect_GetResourcesCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_GetResourcesCommand_descriptor,
        new java.lang.String[] { });
    internal_static_spark_connect_GetResourcesCommandResult_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_spark_connect_GetResourcesCommandResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_GetResourcesCommandResult_descriptor,
        new java.lang.String[] { "Resources", });
    internal_static_spark_connect_GetResourcesCommandResult_ResourcesEntry_descriptor =
      internal_static_spark_connect_GetResourcesCommandResult_descriptor.getNestedTypes().get(0);
    internal_static_spark_connect_GetResourcesCommandResult_ResourcesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_spark_connect_GetResourcesCommandResult_ResourcesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
    org.apache.spark.connect.proto.Common.getDescriptor();
    org.apache.spark.connect.proto.Expressions.getDescriptor();
    org.apache.spark.connect.proto.Relations.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
